In [1]:
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

In [34]:
def hungarian(cost_matrix_np):
    n = cost_matrix_np.shape[0]
    
    rows = cost_matrix_np.shape[0]
    cols = cost_matrix_np.shape[0]
    
    for row in np.arange(0, rows):
        row_min = np.min(cost_matrix_np[row, :])
        cost_matrix_np[row, :] -= row_min
    
    for col in np.arange(0, cols):
        col_min = np.min(cost_matrix_np[:, col])
        cost_matrix_np[:, col] -= col_min
        
    print(cost_matrix)
       
    #(1)
    rows_with_zeros = []
    for row in np.arange(0, rows):
        indices = cost_matrix[row, cost_matrix[row, :] == 0]
        if len(indices) > 1:
            print('row: ', row)
            rows_with_zeros.append(([row, np.arange(0, cols)], len(indices)))
            
    print('Rows with zeros in them: ', rows_with_zeros)
    
    #(2) Check which line has the most zeros
    lines = None
    
    prev_n_zeros = 0
    max_idx = 0
    max_row = 0
    for idx in np.arange(0, len(rows_with_zeros)):
        n_zeros = rows_with_zeros[idx][1]
        if n_zeros > prev_n_zeros:
            max_idx = idx
            max_row = rows_with_zeros[idx][0][0]
            prev_n_zeros = n_zeros
            
    lines = [rows_with_zeros[max_idx]]
    
    while 1:
        #(3) Check the columns for zeros
        for col in np.arange(max_row, cols):
            indices = cost_matrix[max_row, cost_matrix[max_row, col] == 0][0]
            nindices = len(indices)
            if nindices > 1:
                print('col: ', indices)
                lines.append(([max_row, np.arange(0, cols)], nindices))

        print('Number of lines: ', len(lines))
        print(lines)
        
        if len(lines) == n:
            print('\nFound optimum!\n')
            break
        
        #(4) Find smallest entry and subtract from all
        min_value = 100000000000000
        location = None
        for row in np.arange(0, rows):
            for col in np.arange(0, cols):
                if min_value > cost_matrix_np[row, col] and cost_matrix_np[row, col] != 0:
                    print(cost_matrix_np[row, col])
                    min_value = cost_matrix_np[row, col]
                    location = (row, col)
                    
        min_row_value = cost_matrix_np[location[0], location[1]]
        
        if location is not None:
            for row in np.arange(0, rows):
                if np.count_nonzero(cost_matrix_np[row, :]) == 0: 
                    continue
                cost_matrix_np[row, :] -= min_row_value
        
        print(cost_matrix_np)
        
        #(5) Add entry to all covered columns (from lines)
        
        
        raise('debug')
    
    return lines

In [35]:
cost_matrix_optimal = np.array([
    [2500, 4000, 3500],
    [4000, 6000, 3500],
    [2000, 4000, 2500]
])

cost_matrix = np.array([
    [1500, 4000, 4500],
    [2000, 6000, 3500],
    [2000, 4000, 2500]
])

assignments = hungarian(cost_matrix)

print(assignments)

[[   0  500 2500]
 [   0 2000 1000]
 [   0    0    0]]
row:  2
Rows with zeros in them:  [([2, array([0, 1, 2])], 3)]
col:  [0 0 0]
Number of lines:  2
[([2, array([0, 1, 2])], 3), ([2, array([0, 1, 2])], 3)]
500
[[-500    0 2000]
 [-500 1500  500]
 [   0    0    0]]


TypeError: exceptions must derive from BaseException