In [1]:
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

In [13]:
def hungarian(cost_matrix_np):
    rows = cost_matrix_np.shape[0]
    cols = cost_matrix_np.shape[0]
    
    for row in np.arange(0, rows):
        row_min = np.min(cost_matrix_np[row, :])
        cost_matrix_np[row, :] -= row_min
    
    for col in np.arange(0, cols):
        col_min = np.min(cost_matrix_np[:, col])
        cost_matrix_np[:, col] -= col_min
            
    print(cost_matrix_np)

In [14]:
cost_matrix = np.array([
    [2500, 4000, 3500],
    [4000, 6000, 3500],
    [2000, 4000, 2500]
])

assignments = hungarian(cost_matrix)

print(assignments)

[[   0    0 1000]
 [ 500 1000    0]
 [   0  500  500]]
None
